#
# Copyright (C) 2014 Cisco Systems, Inc.
#
# Author: Luka Perkov <luka.perkov@sartura.hr>
# Author: Petar Koretic <petar.koretic@sartura.hr>
#
# testconf is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# You should have received a copy of the GNU General Public License
# along with testconf. If not, see <http://www.gnu.org/licenses/>.
#

all: test-all

test-all:
	node generic_rpc_get.js
	node syslog_rpc_edit_config.js
	node syslog_rpc_get.js
