/* autogenerated by testconf */

/* 2014/24/09 16:51 */

/*
 * Copyright (C) 2014 Cisco Systems, Inc.
 *
 * Author: Petar Koretic <petar.koretic@sartura.hr>
 * Author: Luka Perkov <luka.perkov@sartura.hr>
 *
 * testconf is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * You should have received a copy of the GNU General Public License
 * along with testconf. If not, see <http://www.gnu.org/licenses/>.
 */

var exec = require('child_process').exec;

var netconf = require('./../../core/netconf')

var json_path = require('JSONPath')

var methods = netconf.create_default_methods()

module.exports = methods

methods["namespace"] = { "xmlns" : "urn:ietf:params:xml:ns:yang:ietf-syslog" }

// non mandatory values are commented out

/* get
	method return structure:
	return object for data
		return { }
	return string if error
		return "error message"
*/

netconf.add_method(methods["get"], "$..syslog[*]", function(filter)
{

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..global-logging[*]", function(filter)
{
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..console-logging[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..file-logging[*]", function(filter)
{
	//console.log(input['file-name'][0]) //string
	//input['file-size'][0] //uint32
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..remote-logging[*]", function(filter)
{

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..terminal-logging[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity
	//input['uname'][0] //string
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

netconf.add_method(methods["get"], "$..syslog[*]..terminal-logging[*]..all-users[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

/* get-config
	return object for data
		return { }
	return string if error
		return "error message"
*/
netconf.add_method(methods["get-config"], "$..syslog[*]", function(filter)
{

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..global-logging[*]", function(filter)
{
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..console-logging[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..file-logging[*]", function(filter)
{
	//console.log(input['file-name'][0]) //string
	//input['file-size'][0] //uint32
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..remote-logging[*]", function(filter)
{

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..terminal-logging[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity
	//input['uname'][0] //string
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})
netconf.add_method(methods["get-config"], "$..syslog[*]..terminal-logging[*]..all-users[*]", function(filter)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

	return { }
})

/* edit-config
	method return structure:
	return { code : int, msg : string}
	code - nonzero for error, msg - error message
	returns ok by default
*/

netconf.add_method(methods["edit-config"], "$..syslog[*]", function(input)
{

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..global-logging[*]", function(input)
{
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..console-logging[*]", function(input)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..file-logging[*]", function(input)
{
	//console.log(input['file-name'][0]) //string
	//input['file-size'][0] //uint32
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..remote-logging[*]", function(input)
{

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..terminal-logging[*]", function(input)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity
	//input['uname'][0] //string
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

})


netconf.add_method(methods["edit-config"], "$..syslog[*]..terminal-logging[*]..all-users[*]", function(input)
{
	//input['logging-severity'][0] //syslogtypes:Severity
	//input['facility'][0] //identityref
	//input['severity'][0] //syslogtypes:Severity

})


